### ISSUE TITLE
Contabilizador de respuestas

### ISSUE THREAD

**Issue by heyJ0NG** [BetsyZV/Trivia#1]
Es un buen trabajo, como recomendación estaria genial agregar un contador de respuestas correctas e incorrectas para poder ver un resumen del juego.
![mejora](https://user-images.githubusercontent.com/113320318/190004253-aca2783c-6b23-49d5-9e9e-77592f029690.jpg)

**Comment by BetsyZV** [comment]
En el link, se encuentra modificada la trivia considerando cuántas respuestas correctas e incorrectas  realizaste
en el juego. Gracias por la recomendación!!

https://replit.com/@BetsyZapata/himundo

![tr](https://user-images.githubusercontent.com/113310193/190930637-9e7eaec7-fefd-4ab9-81b6-1816ab469596.jpg)
